import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@src/components/layouts/Navbar";
import { Footer } from "@src/components/layouts/Footer";

export const metadata: Metadata = {
  title: "Sanjay Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <>
          <Navbar />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
